apiVersion: v2
name: vinoselecto
description: Full stack application
type: application
version: 1.0.0
dependencies:
  - name: backend
    version: "1.0.0"
    repository: "file://./charts/backend"
    condition: backend.enabled
  - name: frontend
    version: "1.0.0"
    repository: "file://./charts/frontend"
    condition: frontend.enabled
